// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Device.DeviceKind (no DeviceLabel): la migración F1 sustituyó la columna de
// texto libre device_label por device_kind, un vocabulario cerrado (movil,
// tablet, laptop, escritorio, otro) — ver plan/01_Base_de_datos.md §3.4. F3
// copió este archivo verbatim desde ../usbi sin detectar el desajuste contra
// el esquema ya decidido; se corrige en F4 al tocar el paquete devices para
// la saga ARCO (MarkUserDevicesForWipe). Esto rompe deliberadamente el
// diff-cero de internal/devices contra ../usbi.
type Device struct {
	ID            uuid.UUID    `json:"id"`
	UserID        uuid.UUID    `json:"user_id"`
	DeviceKind    string       `json:"device_kind"`
	Platform      string       `json:"platform"`
	RegisteredAt  time.Time    `json:"registered_at"`
	LastSeenAt    time.Time    `json:"last_seen_at"`
	WipeLocalData bool         `json:"wipe_local_data"`
	RevokedAt     sql.NullTime `json:"revoked_at"`
}

type Level struct {
	ID               uuid.UUID       `json:"id"`
	SectionID        uuid.UUID       `json:"section_id"`
	Title            string          `json:"title"`
	Color            string          `json:"color"`
	TemplateType     string          `json:"template_type"`
	Content          json.RawMessage `json:"content"`
	Difficulty       int32           `json:"difficulty"`
	IsPublished      bool            `json:"is_published"`
	CreatedByAdminID uuid.NullUUID   `json:"created_by_admin_id"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	DeletedAt        sql.NullTime    `json:"deleted_at"`
	DeletedBy        uuid.NullUUID   `json:"deleted_by"`
}

type Section struct {
	ID               uuid.UUID     `json:"id"`
	Title            string        `json:"title"`
	Description      string        `json:"description"`
	Color            string        `json:"color"`
	CreatedByAdminID uuid.NullUUID `json:"created_by_admin_id"`
	IsPublished      bool          `json:"is_published"`
	CreatedAt        time.Time     `json:"created_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
	ArchivedAt       sql.NullTime  `json:"archived_at"`
}
