// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AdminAuditLog struct {
	ID          uuid.UUID             `json:"id"`
	ActorUserID uuid.NullUUID         `json:"actor_user_id"`
	Action      string                `json:"action"`
	EntityType  string                `json:"entity_type"`
	EntityID    uuid.NullUUID         `json:"entity_id"`
	BeforeState pqtype.NullRawMessage `json:"before_state"`
	AfterState  pqtype.NullRawMessage `json:"after_state"`
	IpAddress   string                `json:"ip_address"`
	UserAgent   string                `json:"user_agent"`
	CreatedAt   time.Time             `json:"created_at"`
}

type Badge struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	XpThreshold int32     `json:"xp_threshold"`
	IconKey     string    `json:"icon_key"`
}

type DailyStreak struct {
	UserID       uuid.UUID `json:"user_id"`
	ActivityDate time.Time `json:"activity_date"`
}

type Device struct {
	ID            uuid.UUID    `json:"id"`
	UserID        uuid.UUID    `json:"user_id"`
	DeviceLabel   string       `json:"device_label"`
	Platform      string       `json:"platform"`
	RegisteredAt  time.Time    `json:"registered_at"`
	LastSeenAt    time.Time    `json:"last_seen_at"`
	WipeLocalData bool         `json:"wipe_local_data"`
	RevokedAt     sql.NullTime `json:"revoked_at"`
}

type ExperienceHistory struct {
	ID                 uuid.UUID     `json:"id"`
	UserID             uuid.NullUUID `json:"user_id"`
	LevelID            uuid.UUID     `json:"level_id"`
	EventType          string        `json:"event_type"`
	XpGained           int32         `json:"xp_gained"`
	Source             string        `json:"source"`
	VerificationMethod string        `json:"verification_method"`
	SyncEventID        uuid.NullUUID `json:"sync_event_id"`
	CreatedAt          time.Time     `json:"created_at"`
}

type Level struct {
	ID               uuid.UUID       `json:"id"`
	SectionID        uuid.UUID       `json:"section_id"`
	Title            string          `json:"title"`
	Color            string          `json:"color"`
	TemplateType     string          `json:"template_type"`
	Content          json.RawMessage `json:"content"`
	Difficulty       int32           `json:"difficulty"`
	IsPublished      bool            `json:"is_published"`
	CreatedByAdminID uuid.NullUUID   `json:"created_by_admin_id"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	DeletedAt        sql.NullTime    `json:"deleted_at"`
	DeletedBy        uuid.NullUUID   `json:"deleted_by"`
}

type LevelAttempt struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	LevelID       uuid.UUID `json:"level_id"`
	AttemptDate   time.Time `json:"attempt_date"`
	AttemptNumber int32     `json:"attempt_number"`
	XpAwarded     int32     `json:"xp_awarded"`
	Completed     bool      `json:"completed"`
	CreatedAt     time.Time `json:"created_at"`
}

type PlayerProgress struct {
	UserID           uuid.UUID    `json:"user_id"`
	LevelID          uuid.UUID    `json:"level_id"`
	BestScore        int32        `json:"best_score"`
	XpTotalForLevel  int32        `json:"xp_total_for_level"`
	AttemptsCount    int32        `json:"attempts_count"`
	FirstCompletedAt sql.NullTime `json:"first_completed_at"`
	LastCompletedAt  sql.NullTime `json:"last_completed_at"`
}

type Section struct {
	ID               uuid.UUID     `json:"id"`
	Title            string        `json:"title"`
	Description      string        `json:"description"`
	Color            string        `json:"color"`
	CreatedByAdminID uuid.NullUUID `json:"created_by_admin_id"`
	IsPublished      bool          `json:"is_published"`
	CreatedAt        time.Time     `json:"created_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
	ArchivedAt       sql.NullTime  `json:"archived_at"`
}

type SecurityIncident struct {
	ID                   uuid.UUID    `json:"id"`
	DetectedAt           time.Time    `json:"detected_at"`
	ReportedAt           sql.NullTime `json:"reported_at"`
	Severity             string       `json:"severity"`
	AffectedScope        string       `json:"affected_scope"`
	Description          string       `json:"description"`
	ContainmentActions   string       `json:"containment_actions"`
	ResolvedAt           sql.NullTime `json:"resolved_at"`
	ReportedToCutai      bool         `json:"reported_to_cutai"`
	NotifiedToCutaiAt    sql.NullTime `json:"notified_to_cutai_at"`
	NotifiedToSubjectsAt sql.NullTime `json:"notified_to_subjects_at"`
	EvidenceHash         []byte       `json:"evidence_hash"`
}

type SyncEvent struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	DeviceID         uuid.UUID       `json:"device_id"`
	Payload          json.RawMessage `json:"payload"`
	PayloadHash      []byte          `json:"payload_hash"`
	HmacSignature    []byte          `json:"hmac_signature"`
	CryptoKeyVersion int16           `json:"crypto_key_version"`
	HmacValid        bool            `json:"hmac_valid"`
	Status           string          `json:"status"`
	ReceivedAt       time.Time       `json:"received_at"`
	ProcessedAt      sql.NullTime    `json:"processed_at"`
	RejectionReason  sql.NullString  `json:"rejection_reason"`
}

type UserBadge struct {
	UserID   uuid.UUID `json:"user_id"`
	BadgeID  uuid.UUID `json:"badge_id"`
	EarnedAt time.Time `json:"earned_at"`
}
