// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createLevel = `-- name: CreateLevel :exec
INSERT INTO levels (
    id, section_id, title, color, template_type, content, difficulty, is_published, created_by_admin_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateLevelParams struct {
	ID               uuid.UUID       `json:"id"`
	SectionID        uuid.UUID       `json:"section_id"`
	Title            string          `json:"title"`
	Color            string          `json:"color"`
	TemplateType     string          `json:"template_type"`
	Content          json.RawMessage `json:"content"`
	Difficulty       int32           `json:"difficulty"`
	IsPublished      bool            `json:"is_published"`
	CreatedByAdminID uuid.NullUUID   `json:"created_by_admin_id"`
}

func (q *Queries) CreateLevel(ctx context.Context, arg CreateLevelParams) error {
	_, err := q.db.ExecContext(ctx, createLevel,
		arg.ID,
		arg.SectionID,
		arg.Title,
		arg.Color,
		arg.TemplateType,
		arg.Content,
		arg.Difficulty,
		arg.IsPublished,
		arg.CreatedByAdminID,
	)
	return err
}

const createSection = `-- name: CreateSection :exec
INSERT INTO sections (
    id, title, color, is_published, created_by_admin_id
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateSectionParams struct {
	ID               uuid.UUID     `json:"id"`
	Title            string        `json:"title"`
	Color            string        `json:"color"`
	IsPublished      bool          `json:"is_published"`
	CreatedByAdminID uuid.NullUUID `json:"created_by_admin_id"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) error {
	_, err := q.db.ExecContext(ctx, createSection,
		arg.ID,
		arg.Title,
		arg.Color,
		arg.IsPublished,
		arg.CreatedByAdminID,
	)
	return err
}

const getLevelAttemptsByDate = `-- name: GetLevelAttemptsByDate :one
SELECT COUNT(*) as attempt_number
FROM level_attempts
WHERE user_id = $1 AND level_id = $2 AND attempt_date = $3
`

type GetLevelAttemptsByDateParams struct {
	UserID      uuid.UUID `json:"user_id"`
	LevelID     uuid.UUID `json:"level_id"`
	AttemptDate time.Time `json:"attempt_date"`
}

func (q *Queries) GetLevelAttemptsByDate(ctx context.Context, arg GetLevelAttemptsByDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLevelAttemptsByDate, arg.UserID, arg.LevelID, arg.AttemptDate)
	var attempt_number int64
	err := row.Scan(&attempt_number)
	return attempt_number, err
}

const insertExperienceHistory = `-- name: InsertExperienceHistory :exec
INSERT INTO experience_history (
    id, user_id, level_id, event_type, xp_gained, source, verification_method, sync_event_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertExperienceHistoryParams struct {
	ID                 uuid.UUID     `json:"id"`
	UserID             uuid.NullUUID `json:"user_id"`
	LevelID            uuid.UUID     `json:"level_id"`
	EventType          string        `json:"event_type"`
	XpGained           int32         `json:"xp_gained"`
	Source             string        `json:"source"`
	VerificationMethod string        `json:"verification_method"`
	SyncEventID        uuid.NullUUID `json:"sync_event_id"`
}

func (q *Queries) InsertExperienceHistory(ctx context.Context, arg InsertExperienceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertExperienceHistory,
		arg.ID,
		arg.UserID,
		arg.LevelID,
		arg.EventType,
		arg.XpGained,
		arg.Source,
		arg.VerificationMethod,
		arg.SyncEventID,
	)
	return err
}

const insertLevelAttempt = `-- name: InsertLevelAttempt :exec
INSERT INTO level_attempts (
    id, user_id, level_id, attempt_date, attempt_number, xp_awarded, completed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertLevelAttemptParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	LevelID       uuid.UUID `json:"level_id"`
	AttemptDate   time.Time `json:"attempt_date"`
	AttemptNumber int32     `json:"attempt_number"`
	XpAwarded     int32     `json:"xp_awarded"`
	Completed     bool      `json:"completed"`
}

func (q *Queries) InsertLevelAttempt(ctx context.Context, arg InsertLevelAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertLevelAttempt,
		arg.ID,
		arg.UserID,
		arg.LevelID,
		arg.AttemptDate,
		arg.AttemptNumber,
		arg.XpAwarded,
		arg.Completed,
	)
	return err
}

const insertSyncEvent = `-- name: InsertSyncEvent :exec
INSERT INTO sync_events (
    id, device_id, user_id, payload, payload_hash, hmac_signature, crypto_key_version, hmac_valid, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertSyncEventParams struct {
	ID               uuid.UUID       `json:"id"`
	DeviceID         uuid.UUID       `json:"device_id"`
	UserID           uuid.UUID       `json:"user_id"`
	Payload          json.RawMessage `json:"payload"`
	PayloadHash      []byte          `json:"payload_hash"`
	HmacSignature    []byte          `json:"hmac_signature"`
	CryptoKeyVersion int16           `json:"crypto_key_version"`
	HmacValid        bool            `json:"hmac_valid"`
	Status           string          `json:"status"`
}

func (q *Queries) InsertSyncEvent(ctx context.Context, arg InsertSyncEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSyncEvent,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.Payload,
		arg.PayloadHash,
		arg.HmacSignature,
		arg.CryptoKeyVersion,
		arg.HmacValid,
		arg.Status,
	)
	return err
}

const listPublishedLevels = `-- name: ListPublishedLevels :many
SELECT id, section_id, title, color, template_type, difficulty, created_at
FROM levels
WHERE is_published = true AND (id > $1 OR $1 = '00000000-0000-0000-0000-000000000000'::uuid)
ORDER BY id ASC
LIMIT $2
`

type ListPublishedLevelsParams struct {
	Cursor   uuid.UUID `json:"cursor"`
	PageSize int32     `json:"page_size"`
}

type ListPublishedLevelsRow struct {
	ID           uuid.UUID `json:"id"`
	SectionID    uuid.UUID `json:"section_id"`
	Title        string    `json:"title"`
	Color        string    `json:"color"`
	TemplateType string    `json:"template_type"`
	Difficulty   int32     `json:"difficulty"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListPublishedLevels(ctx context.Context, arg ListPublishedLevelsParams) ([]ListPublishedLevelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedLevels, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedLevelsRow
	for rows.Next() {
		var i ListPublishedLevelsRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Title,
			&i.Color,
			&i.TemplateType,
			&i.Difficulty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAdminAudit = `-- name: LogAdminAudit :exec
INSERT INTO admin_audit_log (
    id, actor_user_id, action, entity_type, entity_id, before_state, after_state, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type LogAdminAuditParams struct {
	ID          uuid.UUID             `json:"id"`
	ActorUserID uuid.NullUUID         `json:"actor_user_id"`
	Action      string                `json:"action"`
	EntityType  string                `json:"entity_type"`
	EntityID    uuid.NullUUID         `json:"entity_id"`
	BeforeState pqtype.NullRawMessage `json:"before_state"`
	AfterState  pqtype.NullRawMessage `json:"after_state"`
	IpAddress   string                `json:"ip_address"`
	UserAgent   string                `json:"user_agent"`
}

func (q *Queries) LogAdminAudit(ctx context.Context, arg LogAdminAuditParams) error {
	_, err := q.db.ExecContext(ctx, logAdminAudit,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeState,
		arg.AfterState,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const updateSyncEventStatus = `-- name: UpdateSyncEventStatus :exec
UPDATE sync_events SET status = $2, processed_at = NOW() WHERE id = $1
`

type UpdateSyncEventStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSyncEventStatus(ctx context.Context, arg UpdateSyncEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncEventStatus, arg.ID, arg.Status)
	return err
}

const upsertDailyStreak = `-- name: UpsertDailyStreak :exec
INSERT INTO daily_streak (
    user_id, activity_date
) VALUES (
    $1, $2
) ON CONFLICT (user_id, activity_date) DO NOTHING
`

type UpsertDailyStreakParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ActivityDate time.Time `json:"activity_date"`
}

func (q *Queries) UpsertDailyStreak(ctx context.Context, arg UpsertDailyStreakParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyStreak, arg.UserID, arg.ActivityDate)
	return err
}

const upsertPlayerProgress = `-- name: UpsertPlayerProgress :exec
INSERT INTO player_progress (
    user_id, level_id, best_score, xp_total_for_level, attempts_count, first_completed_at, last_completed_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
) ON CONFLICT (user_id, level_id) DO UPDATE SET
    best_score = GREATEST(player_progress.best_score, EXCLUDED.best_score),
    xp_total_for_level = player_progress.xp_total_for_level + EXCLUDED.xp_total_for_level,
    attempts_count = player_progress.attempts_count + 1,
    last_completed_at = NOW()
`

type UpsertPlayerProgressParams struct {
	UserID          uuid.UUID `json:"user_id"`
	LevelID         uuid.UUID `json:"level_id"`
	BestScore       int32     `json:"best_score"`
	XpTotalForLevel int32     `json:"xp_total_for_level"`
	AttemptsCount   int32     `json:"attempts_count"`
}

func (q *Queries) UpsertPlayerProgress(ctx context.Context, arg UpsertPlayerProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerProgress,
		arg.UserID,
		arg.LevelID,
		arg.BestScore,
		arg.XpTotalForLevel,
		arg.AttemptsCount,
	)
	return err
}
