// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const insertExperienceHistory = `-- name: InsertExperienceHistory :exec
INSERT INTO experience_history (
    id, user_id, level_id, event_type, xp_gained, source, verification_method, sync_event_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertExperienceHistoryParams struct {
	ID                 uuid.UUID     `json:"id"`
	UserID             uuid.NullUUID `json:"user_id"`
	LevelID            uuid.UUID     `json:"level_id"`
	EventType          string        `json:"event_type"`
	XpGained           int32         `json:"xp_gained"`
	Source             string        `json:"source"`
	VerificationMethod string        `json:"verification_method"`
	SyncEventID        uuid.NullUUID `json:"sync_event_id"`
}

func (q *Queries) InsertExperienceHistory(ctx context.Context, arg InsertExperienceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertExperienceHistory,
		arg.ID,
		arg.UserID,
		arg.LevelID,
		arg.EventType,
		arg.XpGained,
		arg.Source,
		arg.VerificationMethod,
		arg.SyncEventID,
	)
	return err
}

const insertLevelAttempt = `-- name: InsertLevelAttempt :exec
INSERT INTO level_attempts (
    id, user_id, level_id, attempt_date, attempt_number, xp_awarded, completed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertLevelAttemptParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	LevelID       uuid.UUID `json:"level_id"`
	AttemptDate   time.Time `json:"attempt_date"`
	AttemptNumber int32     `json:"attempt_number"`
	XpAwarded     int32     `json:"xp_awarded"`
	Completed     bool      `json:"completed"`
}

func (q *Queries) InsertLevelAttempt(ctx context.Context, arg InsertLevelAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertLevelAttempt,
		arg.ID,
		arg.UserID,
		arg.LevelID,
		arg.AttemptDate,
		arg.AttemptNumber,
		arg.XpAwarded,
		arg.Completed,
	)
	return err
}

// LogAuditEntry reemplaza a LogAdminAudit, que insertaba en admin_audit_log.
// Con el rediseño de identidad, admin_audit_log e identity_audit_log se
// fusionan en una sola audit_log (accounts.id, columna actor_account_id) —
// ver plan/04_Rediseno_identidad_gustos.md §1: ya no hay correo que filtrar
// entre las dos bitácoras, así que mantenerlas separadas solo complicaba la
// consulta.
const logAuditEntry = `-- name: LogAuditEntry :exec
INSERT INTO audit_log (
    id, actor_account_id, action, entity_type, entity_id, before_state, after_state, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type LogAuditEntryParams struct {
	ID             uuid.UUID             `json:"id"`
	ActorAccountID uuid.NullUUID         `json:"actor_account_id"`
	Action         string                `json:"action"`
	EntityType     string                `json:"entity_type"`
	EntityID       uuid.NullUUID         `json:"entity_id"`
	BeforeState    pqtype.NullRawMessage `json:"before_state"`
	AfterState     pqtype.NullRawMessage `json:"after_state"`
	IpAddress      string                `json:"ip_address"`
	UserAgent      string                `json:"user_agent"`
}

func (q *Queries) LogAuditEntry(ctx context.Context, arg LogAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, logAuditEntry,
		arg.ID,
		arg.ActorAccountID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeState,
		arg.AfterState,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const updateSyncEventStatus = `-- name: UpdateSyncEventStatus :exec
UPDATE sync_events SET status = $2, processed_at = NOW() WHERE id = $1
`

type UpdateSyncEventStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSyncEventStatus(ctx context.Context, arg UpdateSyncEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncEventStatus, arg.ID, arg.Status)
	return err
}

const upsertDailyStreak = `-- name: UpsertDailyStreak :exec
INSERT INTO daily_streak (
    user_id, activity_date
) VALUES (
    $1, $2
) ON CONFLICT (user_id, activity_date) DO NOTHING
`

type UpsertDailyStreakParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ActivityDate time.Time `json:"activity_date"`
}

func (q *Queries) UpsertDailyStreak(ctx context.Context, arg UpsertDailyStreakParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyStreak, arg.UserID, arg.ActivityDate)
	return err
}
